# Generated by Django 5.1 on 2024-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(default=dict, verbose_name="제품 사양"),
        ),
    ]
