# Generated by Django 5.1 on 2024-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0006_product_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="presentation_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mall/product/presentation/%Y/%m/%d",
                verbose_name="Presentation 이미지",
            ),
        ),
    ]
