# Generated by Django 5.1 on 2024-08-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0008_productoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mall.productoption",
            ),
        ),
    ]
