# Generated by Django 5.1 on 2024-08-27 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0009_cartproduct_option"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartproduct",
            name="unique_user_product",
        ),
        migrations.AddConstraint(
            model_name="cartproduct",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "option"), name="unique_user_product_option"
            ),
        ),
    ]
