# Generated by Django 5.1 on 2024-08-27 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0010_remove_cartproduct_unique_user_product_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderedproduct",
            name="unique_order_product",
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mall.productoption",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderedproduct",
            constraint=models.UniqueConstraint(
                fields=("order", "product", "option"),
                name="unique_order_product_option",
            ),
        ),
    ]
