# Generated by Django 5.1 on 2024-08-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "미결제"),
                    ("paid", "결제완료"),
                    ("cencelled", "결제취소"),
                    ("failed", "결제실패"),
                    ("virtualAccountIssued", "가상계좌"),
                ],
                db_index=True,
                default="ready",
                max_length=23,
            ),
        ),
    ]
